sudo: required
language: go
services:
  - docker

env:
  global:
    - TF_ACC=1
    - TF_LOG=DEBUG
    - SENSU_API_URL=http://127.0.0.1:8080
    - SENSU_USERNAME=admin
    - SENSU_PASSWORD=P@ssw0rd!
    - SENSU_ENVIRONMENT=default
    - SENSU_ORGANIZATION=default
  matrix:
    - SENSU_VERSION="5.0.0"
    - SENSU_VERSION="master"

go:
  - '1.11'

matrix:
  fast_finish: true
  allow_failures:
    - env: SENSU_VERSION="master"

before_install:
  - docker pull sensu/sensu:${SENSU_VERSION}
  - docker run -v /var/lib/sensu:/var/lib/sensu -d --name sensu-backend -p 2380:2380 -p 3000:3000 -p 8080:8080 -p 8081:8081 sensu/sensu:${SENSU_VERSION} sensu-backend start
  - docker run -v /var/lib/sensu:/var/lib/sensu -d --name sensu-agent sensu/sensu:${SENSU_VERSION} sensu-agent start --backend-url ws://localhost:8081 --subscriptions webserver,system --cache-dir /var/lib/sensu

script:
  - make fmtcheck
  - make vet
  - make testacc

before_deploy:
  - make targets

deploy:
  provider: releases
  api_key:
    secure: RizKQUa13pWgyCQQdZsWuCDV3cDr6bR8X4BdpvsjBlJOZF8d6ebZupHOnnaRqrzpJnO1T2oQj9m+BWBjbGEXs0LPpoZK00fwDuxrey7WLX0uqdqScqoEJ/JsdHRQo4wUCH7+/Ft2W3FVN/So/1+lKcCQd27Be10+odBwjg6VxI86iydGbObZ1uKE2V4g3tzurb8NJ3mRtu8h6wAYLYsfYNWRb9uZ+UVjdU+6RwDgmKdwlvHJlL0CakOqUPl4MM4ZcZJB4WUgHTNTiByQZrBuTyHxAsEs7uu574zTjN4KXvNLH4UlDPbHgeZBbmEGdfaohoBdslzoGLEJzJhg6kOBROyg1+7qWXnuKjGRMMk7+UbZ2vHtbmCsQdvmywHnz0to5EbhvZqYX3gzZpyqz5WLvBoh/91O0wh/uFZvVK+gax9Qt5mpRAbE/kqUx7/yzWi27AkAvUaNhygA3Dp8JrEDJAklmfrjCtaXaI0klpnd/o9gDl3OXyfDAUGfBpitVht5NOkT37+8bf97lUeymOHMmDQr7whcCpL17jBazNCKoRnGtr02XYQka/5PcJq2hSrKfKWSLayUDoOJOqMGbi1zy4FjEZMXCb2gXzhR6eJYH3dMs6JdxaI17uANNN74tawG3pKj1UwXcAfz6xOo1OsXDksyqn1G8EB2oRgfiu77COY=
  file: dist/*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: jtopjian/terraform-provider-sensu
    tags: true
    condition: $SENSU_VERSION = "5.0.0"
